Copy uboot.img verbatim and add --add_missing for add_img_to_target_files to fix the following issue
Traceback (most recent call last):
  File "/source/out/soong/host/linux-x86/bin/sign_target_files_apks/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/source/out/soong/host/linux-x86/bin/sign_target_files_apks/internal/stdlib/runpy.py", line 72, in _run_code
  File "/source/out/soong/host/linux-x86/bin/sign_target_files_apks/__main__.py", line 12, in <module>
  File "/source/out/soong/host/linux-x86/bin/sign_target_files_apks/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/source/out/soong/host/linux-x86/bin/sign_target_files_apks/internal/stdlib/runpy.py", line 72, in _run_code
  File "/source/out/soong/host/linux-x86/bin/sign_target_files_apks/sign_target_files_apks.py", line 1420, in <module>
  File "/source/out/soong/host/linux-x86/bin/sign_target_files_apks/sign_target_files_apks.py", line 1413, in main
  File "/source/out/soong/host/linux-x86/bin/sign_target_files_apks/add_img_to_target_files.py", line 1024, in main
  File "/source/out/soong/host/linux-x86/bin/sign_target_files_apks/add_img_to_target_files.py", line 970, in AddImagesToTargetFiles
  File "/source/out/soong/host/linux-x86/bin/sign_target_files_apks/add_img_to_target_files.py", line 606, in CheckAbOtaImages
AssertionError: Failed to find uboot.img

This is because uboot.img is skipped when doing ProcessTargetFiles and not
added when doing add_img_to_target_files. Hence, we need to bypass the
skipping for uboot.img when doing ProcessTargetFiles. However, this will lead
to that /IMAGE directory exists in the output target files zip and
add_img_to_target_files will do nothing then. We need to add --add_missing for
add_img_to_target_files to still add images under /IMAGES to target files zip.

Change-Id: I1ce46467332f8923a1d0709a878e9ec7b23698c8